name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13', '3.12', '3.11', '3.10', '3.9', '3.8', '3.7', '3.6']
        install-via: [pip]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pre-commit pylint

      - name: Run pre-commit hooks
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          pre-commit run --all-files

      - name: Run pylint
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          pylint src/

      - name: Run tests
        run: |
          pytest tests.py
