name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.0, 3.12.0, 3.11.0, 3.10.0, 3.9.0, 3.8.0, 3.7.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run pre-commit hooks
      run: |
        .venv/bin/pre-commit run --all-files
    - name: Run pylint
      run: |
        pip install pylint
        pylint src/
    - name: Run tests
      run: |
        pytest
